"""add event details

Revision ID: 615fbeb0e3af
Revises: 3ad66400e82e
Create Date: 2026-10-09 06:51:05.509291
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615fbeb0e3af'
down_revision: Union[str, None] = '3ad66400e82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('event_name', sa.String(length=200), server_default='Unknown', nullable=False))
    op.add_column('generation_jobs', sa.Column('event_organization', sa.String(length=200), server_default='Unknown', nullable=False))
    op.add_column('generation_jobs', sa.Column('event_date', sa.Date(), server_default='2000-01-01', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_jobs', 'event_date')
    op.drop_column('generation_jobs', 'event_organization')
    op.drop_column('generation_jobs', 'event_name')
    # ### end Alembic commands ###
